blank_issues_enabled: false
contact_links:
  - name: Cyan Docs
    url: https://openair-collective.github.io/openair-cyan/
    about: All the information related to Cyan.
  - name: Cyan Discussions and Support
    url: https://github.com/openair-collective/openair-cyan/discussions
    about: Cyan usage Questions, Feature Requests and Projects.
  - name: Cyan Users Chat
    url: https://openair-collective.github.io/openair-cyan/comments_suggetions/
    about: Chat for feedback, questions and troubleshooting.
  - name: Cyan Discord
    url: https://openair-collective.github.io/openair-cyan/contact/
    about: Chat for feedback, questions and troubleshooting.
